# Generated by Django 5.2.15 on 2026-06-24 07:54

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_store_product_external_product_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='embedding_index', opclasses=['vector_cosine_ops']),
        ),
    ]
